<script setup>
import { computed } from 'vue';
import {
    AdjustmentsHorizontalIcon,
    ArrowRightOnRectangleIcon,
    BellIcon,
    CalendarDaysIcon,
    ChartBarIcon,
    ChartBarSquareIcon,
    CheckCircleIcon,
    ChevronDownIcon,
    Cog6ToothIcon,
    DocumentTextIcon,
    ExclamationTriangleIcon,
    FunnelIcon,
    HomeIcon,
    InformationCircleIcon,
    KeyIcon,
    MagnifyingGlassIcon,
    PencilSquareIcon,
    PhoneIcon,
    PlusIcon,
    ShieldCheckIcon,
    TagIcon,
    TrashIcon,
    TrophyIcon,
    UserCircleIcon,
    UserGroupIcon,
    UserIcon,
    UsersIcon,
    VideoCameraIcon,
    ViewColumnsIcon,
    XMarkIcon,
    Bars3Icon,
    LockClosedIcon,
    NoSymbolIcon,
    ArrowPathIcon,
    EyeIcon,
    EyeSlashIcon,
    GlobeAltIcon,
    ArrowsRightLeftIcon,
    PaperClipIcon,
    ArrowDownTrayIcon,
    ChatBubbleLeftEllipsisIcon,
    ArchiveBoxIcon,
    ClockIcon,
    EnvelopeIcon,
    BuildingOfficeIcon,
    MapPinIcon,
    BanknotesIcon,
    InboxArrowDownIcon,
    DocumentDuplicateIcon,
    ArrowUturnLeftIcon,
    ChevronUpIcon,
    Bars3BottomLeftIcon,
    ListBulletIcon,
    BriefcaseIcon,
    PresentationChartBarIcon,
    LinkIcon,
    SpeakerWaveIcon,
    ClipboardDocumentCheckIcon,
    ChartPieIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronDoubleLeftIcon,
    ChevronDoubleRightIcon,
    EllipsisHorizontalIcon,
    SparklesIcon,
    ArrowTrendingUpIcon,
    ArrowTrendingDownIcon,
    CurrencyRupeeIcon,
    SquaresPlusIcon,
    ArrowUpTrayIcon,
    PhotoIcon,
    SpeakerXMarkIcon,
    BellSlashIcon,
} from '@heroicons/vue/24/outline';

const props = defineProps({ name: { type: String, required: true } });

const icons = {
    home: HomeIcon,
    users: UsersIcon,
    user: UserIcon,
    'user-group': UserGroupIcon,
    'user-circle': UserCircleIcon,
    phone: PhoneIcon,
    video: VideoCameraIcon,
    calendar: CalendarDaysIcon,
    columns: ViewColumnsIcon,
    activity: ChartBarSquareIcon,
    chart: ChartBarIcon,
    trophy: TrophyIcon,
    facebook: GlobeAltIcon,
    shield: ShieldCheckIcon,
    adjustments: AdjustmentsHorizontalIcon,
    tag: TagIcon,
    document: DocumentTextIcon,
    key: KeyIcon,
    cog: Cog6ToothIcon,
    bell: BellIcon,
    search: MagnifyingGlassIcon,
    logout: ArrowRightOnRectangleIcon,
    chevron: ChevronDownIcon,
    plus: PlusIcon,
    edit: PencilSquareIcon,
    trash: TrashIcon,
    close: XMarkIcon,
    menu: Bars3Icon,
    filter: FunnelIcon,
    check: CheckCircleIcon,
    warning: ExclamationTriangleIcon,
    info: InformationCircleIcon,
    lock: LockClosedIcon,
    ban: NoSymbolIcon,
    refresh: ArrowPathIcon,
    eye: EyeIcon,
    'eye-off': EyeSlashIcon,
    switch: ArrowsRightLeftIcon,
    paperclip: PaperClipIcon,
    download: ArrowDownTrayIcon,
    chat: ChatBubbleLeftEllipsisIcon,
    archive: ArchiveBoxIcon,
    clock: ClockIcon,
    envelope: EnvelopeIcon,
    building: BuildingOfficeIcon,
    'map-pin': MapPinIcon,
    money: BanknotesIcon,
    inbox: InboxArrowDownIcon,
    duplicate: DocumentDuplicateIcon,
    restore: ArrowUturnLeftIcon,
    'chevron-up': ChevronUpIcon,
    timeline: Bars3BottomLeftIcon,
    list: ListBulletIcon,
    briefcase: BriefcaseIcon,
    presentation: PresentationChartBarIcon,
    globe: GlobeAltIcon,
    link: LinkIcon,
    speaker: SpeakerWaveIcon,
    'speaker-off': SpeakerXMarkIcon,
    'bell-off': BellSlashIcon,
    upload: ArrowUpTrayIcon,
    photo: PhotoIcon,
    followup: ClipboardDocumentCheckIcon,
    'chart-pie': ChartPieIcon,
    'chevron-left': ChevronLeftIcon,
    'chevron-right': ChevronRightIcon,
    collapse: ChevronDoubleLeftIcon,
    expand: ChevronDoubleRightIcon,
    more: EllipsisHorizontalIcon,
    sparkles: SparklesIcon,
    'trend-up': ArrowTrendingUpIcon,
    'trend-down': ArrowTrendingDownIcon,
    rupee: CurrencyRupeeIcon,
    squares: SquaresPlusIcon,
};

const component = computed(() => icons[props.name] ?? InformationCircleIcon);
</script>

<template>
    <component :is="component" aria-hidden="true" />
</template>
